config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'homes#top'
  get 'search' => 'searches#search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:show, :edit, :update] do
  	member do
  		get :following, :followers
  	end
  end
  get 'users_country/:id' => 'users#show_country', as: 'country'
  resources :posts do
  	resources :post_comments, only: [:new, :create, :destroy]
  	resource :favorites, only: [:create, :destroy]
  end
  resources :direct_messages, only: [:create]
  resources :rooms, only: [:create, :show, :index]
  post 'follow/:id' => 'relationships#follow', as: 'follow'
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # bookの関連付け
  has_many :posts, dependent: :destroy
  # post_commentの関連付け
  has_many :post_comments, dependent: :destroy
  # favoriteの関連付け
  has_many :favorites, dependent: :destroy
  # relationshipの関連付け
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy # フォロー取得
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy # フォロワー取得
  has_many :following_user, through: :follower, source: :followed # 自分がフォーローしている人
  has_many :follower_user, through: :followed, source: :follower # 自分をフォローしている人
  # messageの関連付け
  has_many :direct_message, dependent: :destroy
  # entryの関連付け
  has_many :entries, dependent: :destroy

  # refileのattachment
  attachment :image, destroy: false

  # バリデーション/エラーにする条件
  validates :user_name, presence: true, length: {maximum: 10, minimum: 2}
  validates :account_name, length: {maximum: 20}
  validates :introduction, length: {maximum: 50}

  # sexカラムの選択内容
  enum sex:{
    男性: 0, 女性: 1
  }

  # ユーザーをフォローする
  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  # ユーザーのフォローを外す
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  # フォローしている場合 trueで返す
  def following?(user)
    following_user.include?(user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update]
  def show
	  @user = User.find(params[:id])
    @posts = @user.posts.order(created_at: "DESC")

    # @current_entry = Entry.where(user_id: current_user.id)
    # room_ids = @current_entry.pluck(:room_id)
    # @another_entry = Entry.where(user_id: @user.id)
    # another_entry_room_ids = @another_entry.where(room_id: room_ids).pluck(:room_id)

    # unless @user.id == current_user.id
    #   if another_entry_room_ids.length > 0
    #         @is_room = true
    #         @room_id = room_id[0]
    #   else
    #     @room = Room.new
    #     @entry = Entry.new
    #   end
    # end

    @current_entry = Entry.where(user_id: current_user.id)
    @another_entry = Entry.where(user_id: @user.id)
    unless @user.id == current_user.id
      @current_entry.each do |current|
        @another_entry.each do |another|
          if current.room_id == another.room_id
            @is_room = true
            @room_id = current.room_id
          end
        end
      end
      unless @is_room
        @room = Room.new
        @entry = Entry.new
      end
    end
  end

  def show_country
    @user = User.find(params[:id])
    # linkから受け取る値(all/0/1)で条件分岐
    if params[:country] == "all"
      @posts = @user.posts.order(created_at: "DESC")
    else
      @posts = @user.posts.where(country: params[:country]).order(created_at: "DESC")
    end
  end

  def edit
  	@user = User.find(params[:id])
    # ラジオボタンにチェックしていればtrue/チェックなければfalse
    @man = @user.sex == "男性" ? true : false
    @femalu = @user.sex == "女性" ? true : false
  end

  def update
  	@user = User.find(params[:id])
    # date型に変換
    data = user_params
    data[:sex] = data[:sex].to_i

    if @user.email == "test@example.com"
      redirect_to edit_user_path(@user.id), notice: "* Cannot be edited because it is a guest user"
  	elsif @user.update(data)
  	  redirect_to user_path(@user.id), notice: "* Editing is complete"
  	else
  	  render "edit"
  	end
  end

  def following
    @user = User.find(params[:id])
    @users = @user.following_user
    render 'show_following'
  end

  def followers
    @user = User.find(params[:id])
    @users = @user.follower_user
    render 'show_follower'
  end

  private
  def user_params
  	params.require(:user).permit(:user_name, :account_name, :website, :introduction, :image, :phone_number, :sex)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="row">

	<% if @user.errors.any? %>
	    <div class="col-10 offset-1 mt-5 field_with_errors">
            <div id="error_explanation">
                <h3><%= pluralize(@user.errors.count, "error") %> Please try again:</h3>

                <% @user.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </div>
        </div>
    <% end %>

	<div class="col-10 offset-1">
	    <div class="heading">
		    <h1 class="heading-text">Change registration information</h1>
		</div>
	</div>

</div>

<div class="row mt-5">
    <!-- userのimgae画像 -->
	<div class="col-md-5">
		<div class="user-img">
			<%= attachment_image_tag @user, :image, format: 'jpeg', fallback: "noimg.jpg", size: "180x180", class: "rounded-circle center-block" %>
		</div>
	</div>

	<%= form_for(@user, url: user_path, html: {method: :patch}) do |f| %>
		<div class="user-info col-md-7">

            <!-- 画像変更フィールド -->
			<div class="form-group">
				<%= f.attachment_field :image %>
			</div>

			<!-- 名前変更フィールド -->
			<div class="form-group">
				<%= f.label :user_name, "名前" %>
				<%= f.text_field :user_name %>
			</div>

			<!-- ユーザーネーム変更フィールド -->
			<div class="form-group">
				<%= f.label :account_name, "ユーザーネーム" %>
				<%= f.text_field :account_name %>
			</div>

			<!-- ウェブサイト変更フィールド -->
			<div class="form-group">
				<%= f.label :website, "ウェブサイト" %>
				<%= f.text_field :website %>
			</div>

			<!-- 自己紹介変更フィールド -->
			<div class="form-group">
				<%= f.label :introduction, "自己紹介" %>
				<%= f.text_area :introduction %>
			</div>

            <!-- 電話番号変更フィールド -->
			<div class="form-group">
				<%= f.label :phone_number, "電話番号(ハイフンなし)" %>
				<%= f.text_field :phone_number %>
			</div>

            <!-- 性別変更フィールド -->
			<div class="fadio-inline">
				<%= f.label :sex, :男性 %>
                <%= f.radio_button :sex, 0, checked: @man %>
                <%= f.label :sex, :女性 %>
                <%= f.radio_button :sex, 1, checked: @femalu %>
			</div>

			<!-- 送信ボタン -->
			<div class="actions">
		        <%= f.submit "完了", class: "btn btn-success" %>
	        </div>

		</div>
	<% end %>

</div>

app/views/users/show.html.erb
<div class="row">
    <div class="col-md-12">
    	<div class="heading">
            <h1 class="heading-text">
                <!-- ログインユーザのページかどうか分岐 -->
                <% if current_user == @user %>
                    My page
                <% else %>
                    <% if @user.account_name.present? %>
                        <%= "@#{@user.account_name}" %> page
                    <% else %>
                        <%= @user.user_name %> page
                    <% end %>
                <% end %>
            </h1>
        </div>
    </div>
</div>


<div class="row mt-5">
    <div class="col-md-5">

        <div class="user-img">
            <%= attachment_image_tag @user, :image, format: 'jpeg', fallback: "noimg.jpg", size: "200x200", class: "rounded-circle" %>
        </div>

        <table class="table table-borderless follow">
            <tbody>
                <tr>
                    <th>follows</th>
                    <th><%= link_to @user.follower.count, following_user_path(@user.id) %></th>
                </tr>
                <tr>
                    <th>followers</th>
                    <th><%= link_to @user.followed.count, followers_user_path(@user.id) %></th>
                </tr>
            </tbody>
        </table>

        <div class="sub-btn">
            <div id="relationship">
                <%= render 'shared/relationship', {user: @user} %>
            </div>

            <% if @user == current_user %>
                <%= link_to 'プロフィール変更', edit_user_path(@user.id), class: " button_custom btn btn-success" %><br>
            <% end %>

            <% if @user.id == current_user.id %>
                <%= link_to rooms_path do %>
                    <i class="far fa-envelope"></i>
                <% end %>
            <% end %>

            <% unless @user.id == current_user.id %>
                <% if @is_room == true %>
                    <%= link_to room_path(@room_id) do %>
                        <i class="far fa-envelope"></i>
                    <% end %>
                <% else %>
                    <%= form_for(@room, url: rooms_path, html: {method: :post}) do |f| %>
                        <%= fields_for @entry do |entry| %>
                            <%= entry.hidden_field :user_id, value: @user.id %>
                        <% end %>
                        <%= f.button :type => "submit", style: 'border-style: none;' do %>
                            <i class="far fa-envelope"></i>
                        <% end %>
                    <% end %>
                <% end %>
            <% end %>
        </div>

    </div>

    <div class="col-md-7">
        <table class="table table-borderless info">
            <tbody>

                <tr>
                    <th>User name</th>
                    <td><%= @user.user_name %></td>
                </tr>

                <tr>
                    <th>Account name</th>
                    <td>
                        <% if @user.account_name.present? %>
                            <%= "@#{@user.account_name}" %>
                        <% end %>
                    </td>
                </tr>

                <tr>
                    <th>Introduction</th>
                    <td><%= @user.introduction %></td>
                </tr>

                <tr>
                    <th>Website</th>
                    <td>
                        <% unless @user.website.nil? %>
                            <%= link_to @user.website, @user.website %>
                        <% end %>
                    </td>
                </tr>

                <% if current_user == @user %>

                    <tr>
                        <th>Tel</th>
                        <td><%= @user.phone_number %></td>
                    </tr>

                    <tr>
                        <th>Gender</th>
                        <td><%= @user.sex %></td>
                    </tr>

                    <tr>
                        <th>Mail address</th>
                        <td><%= @user.email %></td>
                    </tr>

                <% end %>
            </tbody>
        </table>
    </div>
</div>

<div class="row mt-5">
    <div class="col-md-12">
        <ul class="nav nav-tabs">
            <li class="nav-item"><%= link_to '全て', country_path(@user.id, country: "all"), method: :get, remote: true, class: "nav-link" %></li>
            <li class="nav-item"><%= link_to '国内', country_path(@user.id, country: 0), method: :get, remote: true, class: "nav-link" %></li>
            <li class="nav-item"><%= link_to '海外', country_path(@user.id, country: 1), method: :get, remote: true, class: "nav-link" %></li>
        </ul>
    </div>
</div>
<!-- country別　非同期 -->
<div class="row" id="country-<%= @user.id %>">
    <%= render 'shared/country', {user: @user} %>
</div>

app/views/users/show_country.js.erb
$("#country-<%= @user.id %>").html("<%= j(render 'shared/country', {user: @user}) %>");

app/views/users/show_follower.html.erb
<div class="row">
	<div class="col-12">
		<div class="heading">
			<h1 class="heading-text">Follower Users</h1>
		</div>
	</div>
</div>


<% if @users.count > 0 %>
    <%= render '/shared/follow', users: @users %>
<% else %>
    <div class="row">
        <div class="col-md-12">
    	    <p>フォローされているユーザーはいません</p>
        </div>
    </div>
<% end %>

app/views/users/show_following.html.erb
<div class="row">
	<div class="col-md-12">
		<div class="heading">
			<h1 class="heading-text">Follower Users</h1>
		</div>
	</div>
</div>


<% if @users.count > 0 %>
	<%= render '/shared/follow', users: @users %>
<% else %>
    <div class="row">
        <div class="col-md-12">
    	    <p>フォローしているユーザーはいません</p>
        </div>
    </div>
<% end %>