config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'homes#top'
  get 'search' => 'searches#search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:show, :edit, :update] do
  	member do
  		get :following, :followers
  	end
  end
  get 'users_country/:id' => 'users#show_country', as: 'country'
  resources :posts do
  	resources :post_comments, only: [:new, :create, :destroy]
  	resource :favorites, only: [:create, :destroy]
  end
  resources :direct_messages, only: [:create]
  resources :rooms, only: [:create, :show, :index]
  post 'follow/:id' => 'relationships#follow', as: 'follow'
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow'
end

app/models/room.rb
class Room < ApplicationRecord
  # messageの関連付け
  has_many :direct_messages, dependent: :destroy
  # entryの関連付け
  has_many :entries, dependent: :destroy
  # refileのattachment
  attachment :image, destroy: false
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def create
  	@room = Room.create
  	current_entry = Entry.create(user_id: current_user.id, room_id: @room.id)
  	another_entry = Entry.create(user_id: params[:entry][:user_id], room_id: @room.id)
  	redirect_to room_path(@room.id)
  end

  def show
    @room = Room.find(params[:id])
  	if Entry.where(user_id: current_user.id, room_id: @room.id)
  	  @direct_messages = @room.direct_messages
  	  @direct_message = DirectMessage.new

   	  @another_user = @room.entries.where.not(user_id: current_user.id).first.user
  	else
  	  redirect_back(fallback_location: posts_path)
  	end
  end

  def index
    current_room_ids = Entry.where(user_id: current_user.id).pluck(:room_id)
    @another_entries = Entry.where(room_id: current_room_ids).where.not(user_id: current_user.id)
  end

end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/index.html.erb
<div class="row">
	<div class="col-md-12">
		<div class="heading">
			<div class="heading-text">Direct Message</div>
		</div>
	</div>
</div>

<% if @another_entries.count > 0 %>
<div class="row">
	<div class="col-md-12">
		<table class="table DM">
			<thead>
				<tr class="DM-info">
					<th>profile image</th>
					<th>name<br>(acount_name)</th>
					<th>DM</th>
				</tr>
			</thead>
			<tbody>
			<% @another_entries.each do |another_entry| %>
				<tr>
					<td><%= attachment_image_tag another_entry.user, :image, format: 'jpeg', fallback: "noimg.jpg", size: "100x100", class: "rounded-circle" %></td>
					<td>
						<% if another_entry.user.account_name.present? %>
						    <%= link_to another_entry.user.user_name, user_path(another_entry.user) %>
						    <%= link_to "(@#{another_entry.user.account_name})", user_path(another_entry.user) %>
						<% else %>
						    <%= link_to another_entry.user.user_name, user_path(another_entry.user) %>
						<% end %>
					</td>
					<td>
						<%= link_to room_path(another_entry.room) do %>
						    <i class="far fa-envelope"></i>
						<% end %>
					</td>
				</tr>
			<% end %>
			</tbody>
		</table>
	</div>
</div>
<% else %>
<div class="row">
    <div class="col-md-12">
   	    <p class="dm-none">DMをしているユーザーはいません</p>
    </div>
</div>
<% end %>

app/views/rooms/show.html.erb
<div class="row">
	<div class="col-md-12">
		<div class="heading">
			<div class="heading-text">
				<%= attachment_image_tag @another_user, :image, format: 'jpeg', fallback: "noimg.jpg", size: "200x200", class: "rounded-circle" %><br>
				<% if @another_user.account_name.present? %>
		            <%= link_to "@#{@another_user.account_name}", user_path(@another_user.id) %>
		        <% else %>
		            <%= link_to @another_user.user_name, user_path(@another_user.id) %>
		        <% end %>
			</div>
		</div>
	</div>
</div>

<div class="row" id="message">
    <%= render 'shared/message', {room: @room} %>
</div>

<div class="row room">
	<div class="dm-form">
		<%= form_for(@direct_message, url: direct_messages_path, html: {method: :post}, remote: true) do |f| %>
		    <%= f.text_field :message, size: "20x10" %>
		    <%= f.hidden_field :room_id, value: @room.id %>
		    <%= f.button :type => "submit", style: 'border-style: none;' do %>
                <i class="far fa-paper-plane"></i>
            <% end %>
		<% end %>
	</div>
</div>