config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'homes#top'
  get 'search' => 'searches#search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:show, :edit, :update] do
  	member do
  		get :following, :followers
  	end
  end
  get 'users_country/:id' => 'users#show_country', as: 'country'
  resources :posts do
  	resources :post_comments, only: [:new, :create, :destroy]
  	resource :favorites, only: [:create, :destroy]
  end
  resources :direct_messages, only: [:create]
  resources :rooms, only: [:create, :show, :index]
  post 'follow/:id' => 'relationships#follow', as: 'follow'
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow'
end

app/models/post.rb
class Post < ApplicationRecord
  # userの関連付け
  belongs_to :user
  # post_imageの関連付け
  has_many :post_images, dependent: :destroy
  # post_commntの関連付け
  has_many :post_comments, dependent: :destroy
  # favoriteの関連付け
  has_many :favorites, dependent: :destroy
  # tag_mapsの関連付け
  has_many :tag_maps, dependent: :destroy
  has_many :tags, through: :tag_maps

  # 複数画像投稿 attachment
  accepts_attachments_for :post_images, attachment: :image

  # バリデーション エラー条件
  validates :country, presence: true
  validates :place, presence: true, length: {maximum: 20}
  validates :body, length: {maximum: 200}
  validate :start_end_check

  # cuntryの選択
  enum country:{
  	国内: 0,
  	海外: 1
  }

  # 投稿内容を最新順に表示（降順）
  scope :recent, -> { order(created_at: :desc) }

  # validate false条件
  def start_end_check
    return true if start_date.blank? || finish_date.blank?
    return true if start_date < finish_date
    errors.add(:finish_date, "の日付を正しく選択してください。")
    false
  end

  # いいねを押しているか判断
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  # 同じtag_nameをまとめる
  def save_tags(savepost_tags)
    current_tags = self.tags.pluck(:tag_name) unless self.tags.nil?
    old_tags = current_tags - savepost_tags
    new_tags = savepost_tags - current_tags

      # 同名のtag_nameが存在する場合 古いtag_nameをdelete
      old_tags.each do |old_name|
        self.tags.delete Tag.find_by(tag_name: old_name)
      end

      # 新しくtag_nameをcreate
      new_tags.each do |new_name|
        post_tag = Tag.find_or_create_by(tag_name: new_name)
        self.tags << post_tag
      end
  end

  # post検索の入力から部分一致で探す
  def self.post_search(post_search)
    if post_search
      @posts = Post.where("place LIKE?","%#{post_search}%")
    end
  end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  def new
  	@post = Post.new
  	# postクラスに関連づいたpost_imageクラスのインスタンス
  	@post.post_images.build
  end

  def index
    # tag検索
    search = params[:search]
    if search.blank?
      @tags = Tag.all
    else
      @tags = Tag.search(search)
    end
    # tagに紐づくpost
    if params[:tag_search]

      if params[:tag_search]
        tag = Tag.find(params[:tag_search])
        @posts = tag.posts.recent
      else
    	  @posts = Post.all.recent
      end
    # post検索
    elsif params[:post_search]

      post_search = params[:post_search]
      if !post_search
        @posts = Post.all.recent
      else
        @posts = Post.post_search(post_search).recent
      end
    # 検索ではない場合
    else
      @posts = Post.all.recent

    end
    #いいね数の上位３つのpost
    @ranks = Post.find(Favorite.group(:post_id).order('count(post_id) desc').limit(3).pluck(:post_id))
  end

  def show
  	@post = Post.find(params[:id])
    @post_comment = PostComment.new
    @post_comments = @post.post_comments
  end

  def create
  	@post = Post.new(post_params)
  	@post.user_id = current_user.id
    # タグの複数投稿 可能
    tag_list = params[:post][:tag_ids].split(',')
  	if @post.save
      @post.save_tags(tag_list)
  	  redirect_to posts_path, notice: "* A record of your trip has been posted"
    else
      render 'new'
    end
  end

  def edit
  	@post = Post.find(params[:id])
  	if current_user != @post.user
  	  redirect_to posts_path
  	end
  end

  def update
  	@post = Post.find(params[:id])
  	if @post.update(post_params)
  	  redirect_to post_path(@post.id), notice: "* Edited the travel record"
    else
      render 'edit'
    end
  end

  def destroy
  	@post = Post.find(params[:id])
    for tag in @post.tags
    tag_count = TagMap.where(tag_id: tag.id).distinct.count

      if tag_count <= 1
        tag.destroy
      end
    end
    @post.destroy
  	redirect_to posts_path
  end

  private
  def post_params
  	params.require(:post).permit(:country, :place, :body, :start_date, :finish_date, :price, post_images_images: [])
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<div class="row">

	<% if @post.errors.any? %>
        <div class="col-10 offset-1 mt-5 field_with_errors">
            <div id="error_explanation">
                <h3><%= pluralize(@post.errors.count, "error") %> prohibited this obj from being saved:</h3>

                <% @post.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </div>
        </div>
    <% end %>

	<div class="col-10 offset-1">
		<div class="heading">
		    <h1 class="heading-text">To edit</h1>
		</div>
	</div>

	<div class="col-6 offset-3 mt-5">
		<div class="group_field">
		<%= form_for(@post, url: post_path, html: {method: :patch}) do |f| %>
		    <!-- country選択フォーム -->
		    <div class="field">
		    	<%= f.label :country, "国内or海外" %><br>
		    	<%= select :post, :country, Post.countries.keys.to_a, include_blank: "選択してください" %>
		    </div>

		    <!-- placeフォーム -->
		    <div class="field">
		    	<%= f.label :place, "Place/行先" %><br>
		    	<%= f.text_field :place, class: "form-control"  %>
		    </div>

		    <!-- bodyフォーム -->
		    <div class="field">
		    	<%= f.label :body, "Review/レビュー" %><br>
		    	<%= f.text_area :body, class: "form-control", :size=>"60x10"  %>
		    </div>

		    <!-- dayフォーム -->
		    <div class="field">
		    	<label>Day/日程</label><br>
		    	<%= f.date_field :start_date %> ~
		    	<%= f.date_field :finish_date %>
		    </div>

		    <!-- priceフォーム -->
		    <div class="field">
		    	<%= f.label :price, "Price/費用" %><br>
		    	<%= f.text_field :price %>
		    </div>

		    <!-- 画像投稿フォーム -->
		    <div class="field">
		    	<%= f.label :post_image, "Picture/思い出の写真" %><br>
		    	<%= f.file_field :post_images_images, multiple: true %>
		    </div>

		    <div class="actions">
		    	<%= f.submit "編集する", class: "btn btn-success" %>
		    </div>
		<% end %>
	    </div>
	</div>
</div>

app/views/posts/index.html.erb
<div class="row">
	<div class="col-10 offset-1">
		<div class="heading">
			<h1 class="heading-text">Take a looking</h1>
		</div>
	</div>
</div>

<div class="row mt-5">
    <strong class="favorite-rank col-md-12">R A N K I N G</strong>
    <% @ranks.each.with_index(1) do |rank_post,i| %>
        <div class="box col-md-4">
            <div class="box-search">
                <h5><%= i %>位</h5>
                <i class="fas fa-crown" style="color: gold;"></i>  
                <%= rank_post.favorites.count %>
            </div>
            <div class="box-top">
                <%= attachment_image_tag rank_post.user, :image, format: 'jpeg', fallback: "noimg.jpg", size: "60x60", class: "rounded-circle" %><br>
                <% if rank_post.user.account_name.present? %>
                    <%= link_to "@#{rank_post.user.account_name}",user_path(rank_post.user) %>
                <% else %>
                    <%= link_to rank_post.user.user_name, user_path(rank_post.user) %>
                <% end %>
            </div>
            <div class="box-text">
                <strong><%= link_to rank_post.place, post_path(rank_post) %></strong>
            </div>
            <% if rank_post.post_images.count < (2) %>
                <% rank_post.post_images.each do |postimage| %>
                <div class="box-main-one">
                    <div class="rank_image_one">
                        <%= attachment_image_tag postimage, :image, class: "image_rank_one" %>
                    </div>
                </div>
                <% end %>
            <% elsif rank_post.post_images.count < (3) %>
                <% rank_post.post_images.each do |postimage| %>
                    <div class="box-main">
                        <%= attachment_image_tag postimage, :image, class: "images_rank_two" %>
                    </div>
                <% end %>
            <% else %>
            <% rank_post.post_images.each do |postimage| %>
            <div class="box-main">
                <%= attachment_image_tag postimage, :image, class: "images_rank" %>
            </div>
            <% end %>
        <% end %>
        </div>
    <% end %>
    <div class="col-md-8">
    <% @posts.each do |post| %>
        <div class="box">
            <div class="box-top">
                <%= attachment_image_tag post.user, :image, format: 'jpeg', fallback: "noimg.jpg", size: "100x100", class: "rounded-circle" %><br>

                <% if post.user.account_name.present? %>
		            <%= link_to "@#{post.user.account_name}", user_path(post.user) %>
		        <% else %>
		            <%= link_to post.user.user_name, user_path(post.user) %>
		        <% end %>
            </div>

            <div class="box-text">
                <%= render 'shared/image_country', {post: post} %>
                <h2><strong><%= link_to post.place, post_path(post.id) %></strong></h2>
                <p><%= safe_join(post.body.split("\n"),tag(:br)) %></p>
                <p class="datatime"><%= post.created_at.strftime('%Y/%m/%d %H:%M') %></p>
                <% post.tags.each do |tag| %>
                    <%= link_to "# #{tag.tag_name}", posts_path(tag_search: tag.id) %>
                <% end %>
            </div>

            <%= render 'shared/postimages', {post: post} %>

            <div class="box-footer">
                <div id="post_comment-modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
                <%= link_to new_post_post_comment_path(post.id), remote: true do %>
                    <i class="far fa-comment-alt"></i>
		            <%= post.post_comments.count %>
                <% end %>
                <label id="favorite-<%= post.id %>">
		        	<%= render 'shared/favorite', {post: post} %>
		        </label>
            </div>

        </div>
    <% end %>
    </div>


    <div class="col-md-4">
        <div class="box">
            <h5 class="box-search">
                <strong>Place Search</strong>
            </h5>
            <div class="search">
                <%= form_tag(posts_path, method: :get) do %>
                    <%= text_field_tag(:post_search) %><%= submit_tag "検索", class: "search-btn" %>
                <% end %>
            </div>
        </div>

    	<div class="box">
    		<h5 class="box-search">
                <strong>Tag Search</strong>
            </h5>
    	    <div class="search">
    	    	<%= form_tag(posts_path, method: :get) do %>
		            <%= text_field_tag(:search) %><%= submit_tag "検索", class: "search-btn" %>
		        <% end %>
		    </div>
		    <div class="search-footer">
		    	<% @tags.each do |tag| %>
		            <%= link_to "# #{tag.tag_name} (#{tag.posts.count}) ", posts_path(tag_search: tag.id) %>
		        <% end %>
		    </div>
	    </div>
    </div>
</div>

app/views/posts/new.html.erb
<div class="row">

	<% if @post.errors.any? %>
        <div class="col-12 mt-5 field_with_errors">
            <div id="error_explanation">
                <h3><%= pluralize(@post.errors.count, "error") %> prohibited this obj from being saved:</h3>

                <% @post.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </div>
        </div>
    <% end %>

	<%= render 'shared/newform', post: @post %>
</div>

app/views/posts/show.html.erb
<div class="row">
	<div class="col-12">
		<div class="heading">
			<h1 class="heading-text">
                <% if current_user == @post.user %>
                    My post
                <% elsif @post.user.account_name.present? %>
                    Write by <%= "@#{@post.user.account_name}" %>
                <% else %>
                    Write by <%= @post.user.user_name %>
                <% end %>
            </h1>
		</div>
	</div>
</div>

<div class="box">
	<div class="row">

        <div class="col-md-4 left-box">

            <div class="post-user">
                <%= attachment_image_tag @post.user, :image, format: 'jpeg', fallback: "noimg.jpg", size: "100x100", class: "rounded-circle" %><br>

                <% if @post.user.account_name.present? %>
                    <%= link_to "@#{@post.user.account_name}", user_path(@post.user) %>
                <% else %>
                    <%= link_to @post.user.user_name, user_path(@post.user) %>
                <% end %>
            </div>

            <div class="day">
                <h3>Went to the day/日程</h3>
                <% if @post.start_date.present? && @post.finish_date.present? %>
                    <p><%= @post.start_date.strftime('%Y/%m/%d') %> ~ <%= @post.finish_date.strftime('%Y/%m/%d') %></p>
                <% end %>
                </p>
            </div>

            <div class="price">
                <h3>Price/費用</h3>
                <% if @post.price %>
                    <p><%= @post.price.to_s(:delimited) %>円</p>
                <% end %>
            </div>

        </div>

        <div class="col-md-8 right-box">
            <div class="country-name">
                <%= render 'shared/image_country', {post: @post} %>
            </div>

            <div class="box-text">
                <h2><strong><%= link_to @post.place, post_path(@post.id) %></strong></h2>
                <p><%= safe_join(@post.body.split("\n"),tag(:br)) %></p>
            </div>

            <%= render 'shared/postimages', {post: @post} %>


            <%= render 'shared/box_footer', {post: @post} %>

        </div>
    </div>

</div>

<div class="row">

    <div class="col-10 offset-2">

		<table class="table table-borderless">
			<!-- postに対してのコメント一覧 -->
			<% @post_comments.each do |post_comment| %>
			    <tr>
			    	<th>
			    		<%= attachment_image_tag post_comment.user, :image, format: 'jpeg', fallback: "noimg.jpg", size: "80x80", class: "rounded-circle" %><br>
                        <% if post_comment.user.account_name.present? %>
			    		    <%= "@#{post_comment.user.account_name}" %>
                        <% else %>
                            <%= post_comment.user.user_name %>
                        <% end %>
			    	</th>
			    	<td>
			    		<%= post_comment.comment %>
			    		<% if current_user == post_comment.user %>
			    		    <%= link_to post_post_comment_path(@post,post_comment), method: :delete, data: {confirm: "コメントを削除しますか？"} do %>
		                        <i class="fas fa-trash-alt"></i>
		                    <% end %>
			    		<% end %>
			    	</td>
			    </tr>
		    <% end %>
		</table>
	</div>
</div>