config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'homes#top'
  get 'search' => 'searches#search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:show, :edit, :update] do
  	member do
  		get :following, :followers
  	end
  end
  get 'users_country/:id' => 'users#show_country', as: 'country'
  resources :posts do
  	resources :post_comments, only: [:new, :create, :destroy]
  	resource :favorites, only: [:create, :destroy]
  end
  resources :direct_messages, only: [:create]
  resources :rooms, only: [:create, :show, :index]
  post 'follow/:id' => 'relationships#follow', as: 'follow'
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/direct_message.rb
class DirectMessage < ApplicationRecord
  # userの関連付け
  belongs_to :user
  # roomの関連付け
  belongs_to :room

  # バリデーション
  validates :message, presence: true
end

app/models/entry.rb
class Entry < ApplicationRecord
  # userの関連付け
  belongs_to :user
  # roomの関連付け
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  #userの関連付け
  belongs_to :user
  #postの関連付け
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  # userの関連付け
  belongs_to :user
  # post_imageの関連付け
  has_many :post_images, dependent: :destroy
  # post_commntの関連付け
  has_many :post_comments, dependent: :destroy
  # favoriteの関連付け
  has_many :favorites, dependent: :destroy
  # tag_mapsの関連付け
  has_many :tag_maps, dependent: :destroy
  has_many :tags, through: :tag_maps

  # 複数画像投稿 attachment
  accepts_attachments_for :post_images, attachment: :image

  # バリデーション エラー条件
  validates :country, presence: true
  validates :place, presence: true, length: {maximum: 20}
  validates :body, length: {maximum: 200}
  validate :start_end_check

  # cuntryの選択
  enum country:{
  	国内: 0,
  	海外: 1
  }

  # 投稿内容を最新順に表示（降順）
  scope :recent, -> { order(created_at: :desc) }

  # validate false条件
  def start_end_check
    return true if start_date.blank? || finish_date.blank?
    return true if start_date < finish_date
    errors.add(:finish_date, "の日付を正しく選択してください。")
    false
  end

  # いいねを押しているか判断
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  # 同じtag_nameをまとめる
  def save_tags(savepost_tags)
    current_tags = self.tags.pluck(:tag_name) unless self.tags.nil?
    old_tags = current_tags - savepost_tags
    new_tags = savepost_tags - current_tags

      # 同名のtag_nameが存在する場合 古いtag_nameをdelete
      old_tags.each do |old_name|
        self.tags.delete Tag.find_by(tag_name: old_name)
      end

      # 新しくtag_nameをcreate
      new_tags.each do |new_name|
        post_tag = Tag.find_or_create_by(tag_name: new_name)
        self.tags << post_tag
      end
  end

  # post検索の入力から部分一致で探す
  def self.post_search(post_search)
    if post_search
      @posts = Post.where("place LIKE?","%#{post_search}%")
    end
  end


end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  # userの関連付け
  belongs_to :user
  # postの関連付け
  belongs_to :post
end

app/models/post_image.rb
class PostImage < ApplicationRecord
  # postの関連付け
  belongs_to :post
  # refile用attachment
  attachment :image

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  # userの関連付け
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  # messageの関連付け
  has_many :direct_messages, dependent: :destroy
  # entryの関連付け
  has_many :entries, dependent: :destroy
  # refileのattachment
  attachment :image, destroy: false
end

app/models/tag.rb
class Tag < ApplicationRecord
  # tag_mapの関連付け
  has_many :tag_maps, dependent: :destroy, foreign_key: 'tag_id'
  # postの関連付け
  has_many :posts, through: :tag_maps

  # tag検索の入力されたtag_nameを部分一致で探す
  def self.search(search)
  	if search
  	  @tags = Tag.where("tag_name LIKE?","%#{search}%")
  	end
  end
end

app/models/tag_map.rb
class TagMap < ApplicationRecord
  # postの関連付け
  belongs_to :post
  # tagの関連付け
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # bookの関連付け
  has_many :posts, dependent: :destroy
  # post_commentの関連付け
  has_many :post_comments, dependent: :destroy
  # favoriteの関連付け
  has_many :favorites, dependent: :destroy
  # relationshipの関連付け
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy # フォロー取得
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy # フォロワー取得
  has_many :following_user, through: :follower, source: :followed # 自分がフォーローしている人
  has_many :follower_user, through: :followed, source: :follower # 自分をフォローしている人
  # messageの関連付け
  has_many :direct_message, dependent: :destroy
  # entryの関連付け
  has_many :entries, dependent: :destroy

  # refileのattachment
  attachment :image, destroy: false

  # バリデーション/エラーにする条件
  validates :user_name, presence: true, length: {maximum: 10, minimum: 2}
  validates :account_name, length: {maximum: 20}
  validates :introduction, length: {maximum: 50}

  # sexカラムの選択内容
  enum sex:{
    男性: 0, 女性: 1
  }

  # ユーザーをフォローする
  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  # ユーザーのフォローを外す
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  # フォローしている場合 trueで返す
  def following?(user)
    following_user.include?(user)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  def new
  	@post = Post.new
  	# postクラスに関連づいたpost_imageクラスのインスタンス
  	@post.post_images.build
  end

  def index
    # tag検索
    search = params[:search]
    if search.blank?
      @tags = Tag.all
    else
      @tags = Tag.search(search)
    end
    # tagに紐づくpost
    if params[:tag_search]

      if params[:tag_search]
        tag = Tag.find(params[:tag_search])
        @posts = tag.posts.recent
      else
    	  @posts = Post.all.recent
      end
    # post検索
    elsif params[:post_search]

      post_search = params[:post_search]
      if !post_search
        @posts = Post.all.recent
      else
        @posts = Post.post_search(post_search).recent
      end
    # 検索ではない場合
    else
      @posts = Post.all.recent

    end
    #いいね数の上位３つのpost
    @ranks = Post.find(Favorite.group(:post_id).order('count(post_id) desc').limit(3).pluck(:post_id))
  end

  def show
  	@post = Post.find(params[:id])
    @post_comment = PostComment.new
    @post_comments = @post.post_comments
  end

  def create
  	@post = Post.new(post_params)
  	@post.user_id = current_user.id
    # タグの複数投稿 可能
    tag_list = params[:post][:tag_ids].split(',')
  	if @post.save
      @post.save_tags(tag_list)
  	  redirect_to posts_path, notice: "* A record of your trip has been posted"
    else
      render 'new'
    end
  end

  def edit
  	@post = Post.find(params[:id])
  	if current_user != @post.user
  	  redirect_to posts_path
  	end
  end

  def update
  	@post = Post.find(params[:id])
  	if @post.update(post_params)
  	  redirect_to post_path(@post.id), notice: "* Edited the travel record"
    else
      render 'edit'
    end
  end

  def destroy
  	@post = Post.find(params[:id])
    for tag in @post.tags
    tag_count = TagMap.where(tag_id: tag.id).distinct.count

      if tag_count <= 1
        tag.destroy
      end
    end
    @post.destroy
  	redirect_to posts_path
  end

  private
  def post_params
  	params.require(:post).permit(:country, :place, :body, :start_date, :finish_date, :price, post_images_images: [])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GoTo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
  </head>

  <body>
    <!--        ヘッダー        -->
    <header class="nav navbar-fixed-to">
      <div class="container">

        <nav class="navbar navbar-expand navbar-dark bg-dark fixed-top">
          <div class="logo">
            <!-- <img src="/assets/go_to.png" alt="ロゴ" width="60" height="60"> -->
            <%= image_tag asset_path("go_to.png", alt: "ロゴ"), class: "header-log" %>
          </div>
          <span>Go to</span>
          <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
              <li><%= link_to ' My page', user_path(current_user), class: "nav-link" %></li>
              <li><%= link_to ' Look', posts_path, class: "nav-link" %></li>
              <li><%= link_to ' Write', new_post_path, class: "nav-link" %></li>
              <li><%= link_to ' DM', rooms_path, class: "nav-link" %></li>
              <li><%= link_to ' Log out', destroy_user_session_path, method: :delete, class: "nav-link" %></li>

            <% else %>
              <li><%= link_to ' Home', root_path, class: "nav-link" %></li>
              <li><%= link_to ' Log in', new_user_session_path, class: "nav-link" %></li>
              <li><%= link_to ' Sign up', new_user_registration_path, class: "nav-link" %></li>

            <% end %>
          </ul>
        </nav>

      </div>
    </header>

    <div class="body">

      <div class="container">
        <div class="col-10 offset-1 mt-5 flash">
          <p id="notice"><%= notice %></p>
        </div>

        <%= yield %>

      </div>

    </div>
  </body>
</html>

app/views/shared/_box_footer.html.erb
            <div class="box-footer">

                <div id="post_comment-modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
                <%= link_to new_post_post_comment_path(post.id), remote: true do %>
                    <i class="far fa-comment-alt"></i>
                    <%= post.post_comments.count %>
                <% end %>

                <label id="favorite-<%= post.id %>">
                    <%= render 'shared/favorite', {post: post} %>
                </label>

                <% if current_user.id == post.user.id %>
                    <%= link_to edit_post_path(post.id) do %>
                        <i class="fas fa-cog"></i>
                    <% end %>

                    <%= link_to post_path(post.id), method: :delete, data: {confirm: "本当に削除してもよろしいですか？"} do %>
                        <i class="fas fa-trash-alt"></i>
                    <% end %>
                <% end %>

            </div>

app/views/shared/_comment.html.erb
<!-- モーダルで表示するフォーム -->
<div class="modal-dialog">
	<div class="modal-content">
		<%= form_for(post_comment,url: post_post_comments_path(post.id), remote: true) do |f| %>
			<%= f.text_area :comment, size: "100x5" %>
		    <%= f.submit '送信', class: 'btn-sm btn-primary' %>
		<% end %>
	</div>
</div>

app/views/shared/_country.html.erb
    <% @posts.each do |post| %>

        <div class="col-md-4 left-box mt-5">

            <div class="country-name">
                <% if post.country == "国内" %>
                    <%= image_tag asset_path("japan.png", alt: "国内"), class: "japan-image" %>
                <% else %>
                    <%= image_tag asset_path("world.png", alt: "国内"), class: "world-image" %>
                <% end %>
            </div>

            <div class="day">
                <h3>Went to the day/日程</h3>
                <% if post.start_date.present? && post.finish_date.present? %>
                    <p><%= post.start_date.strftime('%Y/%m/%d') %> ~ <%= post.finish_date.strftime('%Y/%m/%d') %></p>
                <% end %>
                </p>
            </div>

            <div class="price">
                <h3>Price/費用</h3>
                <% if post.price %>
                    <p><%= post.price.to_s(:delimited) %>円</p>
                <% end %>
            </div>

        </div>

        <div class="col-md-8 right-box mt-5">

            <div class="box-text">
                <h2><strong><%= link_to post.place, post_path(post.id) %></strong></h2>
                <p class="mt-3"><%= safe_join(post.body.split("\n"),tag(:br)) %></p>
                <p class="datatime"><%= post.created_at.strftime('%Y/%m/%d %H:%M') %></p>
            </div>

            <%= render 'shared/postimages', {post: post} %>


            <%= render 'shared/box_footer', {post: post} %>

        </div>

    <% end %>

app/views/shared/_favorite.html.erb
                <!-- いいね非同期 -->
		        <% if post.favorited_by?(current_user) %>
		            <%= link_to post_favorites_path(post.id), method: :delete, remote: true do %>
		                <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
		                <%= post.favorites.count %>
		            <% end %>
		        <% else %>
		            <%= link_to post_favorites_path(post.id), method: :post, remote: true do %>
		                <i class="fa fa-heart-o" aria-hidden="true"></i>
		                <%= post.favorites.count %>
		            <% end %>
		        <% end %>

app/views/shared/_follow.html.erb
    <div class="row">
    	<div class="col-md-12">
	   		<table class="table">
	   			<thead>
	   				<tr>
	   					<th>image</th>
	   				    <th>name<br>(account_name)</th>
	   					<th></th>
	   				</tr>
	   			</thead>
	   			<tbody>
	   			<% users.each do |user| %>
    				<tr>
	    	            <td>
	   		            	<%= attachment_image_tag user, :image, format: 'jpeg', fallback: "noimg.jpg", size: "100x100", class: "rounded-circle" %>
	   		            </td>

	   		            <td>
	   		            	<%= link_to user.user_name, user_path(user.id) %>
	   		            	<% if user.account_name.present? %>
	   		            	    (<%= link_to "@#{user.account_name}", user_path(user.id) %>)
	   		            	<% end %>
	   		            </td>

	   				    <td>
	   				    	<div id="relationship">
                                <%= render 'shared/relationship', {user: user} %>
                            </div>
                        </td>
	   				</tr>
	    		<% end %>
	   			</tbody>
	   		</table>
	   	</div>
    </div>

app/views/shared/_image_country.html.erb
                <% if post.country == "国内" %>
                    <%= image_tag asset_path("japan.png", alt: "国内 "), class: "japan-image"  %>
                <% else %>
                    <%= image_tag asset_path("world.png", alt: "国内"), class: "world-image" %>
                <% end %>

app/views/shared/_message.html.erb
	<div class="col-md-10 offset-1">
		<% room.direct_messages.each do |dm| %>

		    <% if dm.user_id == current_user.id %>
	    	    <div class="current-dm col-4 offset-8">
	    		    <%= dm.message %>
		   	    </div>
		   	<% else %>
		   	    <div class="another-dm col-4 offser-1">
	    		    <%= dm.message %>
		   	    </div>
		   	<% end %>

	    <% end %>
	</div>

app/views/shared/_newform.html.erb
	<div class="col-md-12">
		<div class="heading">
		    <h1 class="heading-text">Take write memories</h1>
		</div>
	</div>

    <div class="col-12 mt-5">
		<div class="group_field">
		<%= form_for(post, url: posts_path, html: {method: :post}) do |f| %>
		    <!-- country選択フォーム -->
		    <div class="field">
		    	<%= f.label :country, "国内or海外" %><br>
		    	<%= select :post, :country, Post.countries.keys.to_a, include_blank: "選択してください" %>
		    </div>

		    <div class="field">
		    	<%= f.label :tag, "Tag/タグ" %>
		    	<%= f.text_field :tag_ids, class: "form-control", id:'tag_ids', placeholder: "※ 複数タグをつけるには ' , ' で区切ってください。" %>
		    </div>

		    <!-- placeフォーム -->
		    <div class="field">
		    	<%= f.label :place, "Place/行先" %><br>
		    	<%= f.text_field :place, class: "form-control" %>
		    </div>

		    <!-- bodyフォーム -->
		    <div class="field">
		    	<%= f.label :body, "Review/レビュー" %><br>
		    	<%= f.text_area :body, class: "form-control", :size=>"60x10" %>
		    </div>

		    <!-- dayフォーム -->
		    <div class="field">
		    	<label>Day/日程</label><br>
		    	<%= f.date_field :start_date %> ~
		    	<%= f.date_field :finish_date %>
		    </div>

		    <!-- priceフォーム -->
		    <div class="field">
		    	<%= f.label :price, "Price/費用" %><br>
		    	<%= f.number_field :price, placeholder: "※ 半角英数字' , 'なし" %> 円
		    </div>

		    <!-- 画像投稿フォーム -->
		    <div class="field">
		    	<%= f.label :post_image, "Picture/思い出の写真" %><br>
		    	<%= f.file_field :post_images_images, multiple: true %>
		    </div>

		    <div class="actions">
		    	<%= f.submit "完了",class: "btn btn-success" %>
		    </div>
		<% end %>
	    </div>
	</div>

app/views/shared/_postimages.html.erb
            <% if post.post_images.count < (2) %>
                <% post.post_images.each do |postimage| %>
                <div class="box-main-one">
                    <%= attachment_image_tag postimage, :image,
                         class: "image_one" %>
                </div>
                <% end %>
            <% elsif post.post_images.count < (3) %>
                <% post.post_images.each do |postimage| %>
                <div class="box-main">
                    <%= attachment_image_tag postimage, :image,  class: "image_two" %>
                </div>
                <% end %>
            <% else %>
                <% post.post_images.each do |postimage| %>
                <div class="box-main">
                    <%= attachment_image_tag postimage, :image, class: "image_list" %>
                </div>
                <% end %>
            <% end %>

app/views/shared/_relationship.html.erb
            <% unless user == current_user %>
                <% if current_user.following?(user) %>
                    <%= link_to 'フォロー中', unfollow_path(user.id), method: :POST, remote: true, class: 'btn btn-primary' %>
                <% else %>
                    <%= link_to 'フォローする', follow_path(user.id), method: :POST, remote: true, class: 'btn btn-success' %>
                <% end %>
            <% end %>